# Here there be a configuration.

# Uncomment as many as you like
log_type error
log_type warning
#log_type notice
log_type information

# When I am debugging, uncomment these lines
#log_type all
log_dest stdout

# 2021-10-10 This does not work
#password_file passwd

# You need this if your clients can't use passwords.
allow_anonymous true


listener 1883
protocol mqtt


listener 9001
protocol websockets


